### ISSUE TITLE
Introduce a UWP app

### ISSUE THREAD

**Issue by AArnott** [AArnott/MoneyMan#1]
Consider leveraging this toolkit: https://github.com/xyzzer/WinRTXamlToolkit

Currently blocked by 
* [ ] dotnet/sdk#707 Can't reference netstandard project from UWP app
* [X] dotnet/roslyn#17178 VS crashes itself shortly after opening solution with .NET Core and UWP project

**Comment by AArnott** [comment]
Currently blocked by https://github.com/dotnet/sdk/issues/707 and https://github.com/dotnet/roslyn/issues/17178

**Comment by sailro** [comment]
What about using https://github.com/Microsoft/UWPCommunityToolkit

**Comment by amoraitis** [comment]
Taking it!

**Comment by AArnott** [comment]
Awesome! Thanks.

**Comment by AArnott** [comment]
I've removed the UWP app because it's insanely hard to get a UWP to build even on Windows, let alone CI, and having to curb the build on mac/linux to skip it, etc. Maybe Project Reunion will make this better, but I gave it a quick spike yesterday and gave up because it too was far too hard.
